### PR TITLE
New version

### PR DESCRIPTION
**Pull request by abdullah-radwan**
New versions. Modifications:
1. Add a command for each effect to toggle.
2. Using the new rotation dataref for versions after 11.02.
3. Reset the view when closing, to help to prevent rotation offset.
4. Modified disable and enable using the command. Disable will restore the initial position. Enable will take the current position as the initial position for later disables.
5. Hide multiscreen compatibility setting in settings window for versions after 11.02, as it no longer needed.
6. Add the command for each effect in the settings menu. 

I've tested it on X-Plane 11.32 on Windows, and it works well. I didn't test on X-Plane 10 or other operating systems, but it should work, as there aren't any modifications in that side.

### CODE REVIEW

**Comment by nico87** [comment]
Thank you for your great contribution.
I checked it out right now and everything seems to work flawlessly.

The only thing I would change is the toggle command listed in the UI. It's great to have it there but now the UI looks more cramped. I would add more vertical space between the checkbox line, the command line and the slider.

**Comment by abdullah-radwan** [comment]
I'll try to work on that. I've left it because the coordination system seems to be too complex.

**Comment by abdullah-radwan** [comment]
I've successfully added https://github.com/simcodersdotcom/headshake/issues/6, with the ability to control the sensitivity, but I didn't add it to the UI yet.
I am thinking about redesigning the UI to X-Plane 11, but that will drop X-Plane 10 compatibility. It's easier and beautiful. I'll try to figure out the coordination system of the old UI if you don't want to drop X-Plane 10 compatibility.

I have a question: What's the gun camera?

**Comment by nico87** [comment]
> I am thinking about redesigning the UI to X-Plane 11, but that will drop X-Plane 10 compatibility. It's easier and beautiful. I'll try to figure out the coordination system of the old UI if you don't want to drop X-Plane 10 compatibility.

We can use the old UI on XP10 and the new one on XP11. I've done it for REP (even tho I used custom windows in there). I'll do some more experiments this afternoon and let you know if it's feasible.

> I have a question: What's the gun camera?

It was designed to make the plane vibrate while shooting the guns, but I never tried to use X-Plane's weapon system.

**Comment by abdullah-radwan** [comment]
Great. I am waiting for you. Currently, the level head camera is working fully as described in the issue. Maximum bank angle is 20, with sensitivity control. I've added it in settings reader and writer also. It just has to be added to the UI.

**Comment by abdullah-radwan** [comment]
Unless somebody will add the gun camera, I'll remove it to clean up the code. I'll keep it if you want.

**Comment by nico87** [comment]
No problem if you remove it. I don't think I'll ever use it.

**Comment by abdullah-radwan** [comment]
Ok. Removed.

**Comment by nico87** [comment]
Do you know if there's a way to use the widgets on a new XPLMCreateWindowEX window? :-/
Seems there's not, as far as I see from the documentation. If I enable the XPLM_USE_NATIVE_WIDGET_WINDOWS feature nothing changes in the window graphics.

**Comment by abdullah-radwan** [comment]
Sorry but I don't really know X-Plane UI SDK. I am so sorry!

**Comment by nico87** [comment]
No problem. I'll look into this again tomorrow but I think moving to a new UI is not a simple task right now since widgets are not supported (it seems).
I have to look further into that! I've opened issue #17 for that.

**Comment by abdullah-radwan** [comment]
I see. Vulkan is also coming, and there might be changes in the SDK. Currently, I'm going to stick with the original UI.

**Comment by abdullah-radwan** [comment]
I've redesigned the UI. I've added level head control and brought multimonitor compatibility back.
This how it looks now: https://i.imgur.com/utBcbnF.png

The third column isn't probably organized. I'd love to hear your suggestions.

**Comment by abdullah-radwan** [comment]
I've [changed the UI slightly](https://i.imgur.com/j5Y7tSt.png) and pushed the changes so you can test.

**Comment by nico87** [comment]
I like the way it is now! I'm going to merge it and release in a few days after a little testing.

Please contact me at support@simcoders.com.

Thank you!

**Comment by abdullah-radwan** [comment]
You are welcome. The following issues should be closed now:
#6 
#13 
#12 
#10

**Pull request merged**
